name: numbrmunchr_api
description: Munches numbers.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

dependencies:
  http: ^1.2.1
  postgres: ^3.1.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  yaml: ^3.1.2

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
